### Taobao dataset
taobao_x0:
    data_root: ../data/Taobao/
    data_format: csv
    train_data: ../data/Taobao/Taobao_x0/train.csv
    valid_data: ../data/Taobao/Taobao_x0/test.csv
    test_data: ../data/Taobao/Taobao_x0/test.csv
    min_categr_count: 10
    feature_cols:
        - {name: price, active: False, dtype: float, type: numeric}
        - {name: ["userid","adgroup_id","pid","cate_id","campaign_id","customer","brand","cms_segid",
                  "cms_group_id","final_gender_code","age_level","pvalue_level","shopping_level","occupation"], 
                  active: True, dtype: str, type: categorical}
        - {name: new_user_class_level, active: False, dtype: str, type: categorical} # All null values in this field
        - {name: hour, active: True, dtype: str, type: categorical, preprocess: convert_hour}
    label_col: {name: clk, dtype: float}
